export default function Head() {
  return (
    <>
      <title>Matcha</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        href="https://unpkg.com/tailwindcss@latest/dist/tailwind.min.css"
        rel="stylesheet"
      />
    </>
  );
}
